Fixing TypeError in error message
It is pretty annoying to get
```File "urequests.py", line 95, in request
TypeError: can't convert 'bytes' object to str implicitly```
instead of being told what was not supported. :-) Fixing