os: Import os.path
On CPython os.path does not need to be imported explicitly.
This fixes the following issue:

>>> import os
>>> os.path.exists("")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  AttributeError: 'module' object has no attribute 'path'