aioble: Fix missing GattError import in server.py
2015-01-01 07:45:46.790 INFO ObjectTransferService Received OLCP_OP_FIRST
2015-01-01 07:45:46.979 ERROR ObjectTransferService Error in ble_write_listener
Traceback (most recent call last):
  File "ots/util.py", line 220, in listener
  File "aioble/server.py", line 223, in indicate
NameError: name 'GattError' isn't defined