fix Traceback in Unix port due to missing 'maxsize'
>>> from machine import I2C
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/.micropython/lib/machine/__init__.py", line 2, in <module>
  File "/root/.micropython/lib/machine/timer.py", line 1, in <module>
  File "/root/.micropython/lib/ffilib.py", line 43, in <module>
AttributeError: 'module' object has no attribute 'maxsize'