hashlib: Fix shadowing of sha256 and sha512 constructors.
hashlib.sha256() and hashlib.sha512() fails with:
TypeError: 'module' object is not callable

This fixes it by renaming the algorithm implementation modules.
Note that 'import hashlib.sha256' is not supported on CPython either,
so we don't need to support that.